### ISSUE TITLE
BossBarAPI is throwing a NullpointerException

### ISSUE THREAD

**Issue by yannicklamprecht** [NavidK0/Carbon-2#19]
Could It be that some attributes are null.

```
java.lang.NullPointerException
at com.lastabyss.carbon.api.BossBar.setMessage(BossBar.java:45) ~[?:?]
at com.lastabyss.carbon.api.BossBarAPI.setMessage(BossBarAPI.java:77) ~[?:?]
```

**Comment by PatoTheBest** [comment]
Will look into it,

**Comment by yannicklamprecht** [comment]
After doing some stuff. I'll look into it too. Hopefully fix it by myself and contribute it.
